# compose.yaml
services:
  frankenphp:
    container_name: dukcapil-laravel
    build:
      context: .
    entrypoint: php artisan octane:frankenphp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - postgres-network  # Menambahkan layanan ke jaringan yang sudah ada

networks:
  postgres-network:
    external: true 
