services:
  frankenphp:
    container_name: dukcapil-laravel
    entrypoint: php artisan octane:frankenphp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - postgres-network  # Menambahkan layanan ke jaringan yang sudah ada
      - nginx-network
networks:
  postgres-network:
    external: true
  nginx-network:
    external: true
