
services:
  frankenphp:
    image: dukcapil-skh-demo:latest
    container_name: dukcapil-laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - postgres-network
      - nginx-network
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

networks:
  postgres-network:
    external: true
  nginx-network:
    external: true

