services:
  frankenphp:
    image: 23.94.64.116:8082/dukcapil-skh-demo:latest
    container_name: dukcapil-laravel
    #entrypoint: php artisan octane:frankenphp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - postgres-network
      - nginx-network

networks:
  postgres-network:
    external: true
  nginx-network:
    external: true