
services:
  frankenphp:
    build:
      context: .
    container_name: dukcapil-laravel
    restart: always
    ports:
      - "8000:8000"
    networks:
      - postgres-network
      - nginx-network
    volumes:
      - .:/app
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

networks:
  postgres-network:
    external: true
  nginx-network:
    external: true

